USE [master]
GO

/****** Object:  Database [DbOrganizer]    Script Date: 11.03.2019 9:59:53 ******/
DROP DATABASE [DbOrganizer]
GO

/****** Object:  Database [DbOrganizer]    Script Date: 11.03.2019 9:59:53 ******/
CREATE DATABASE [DbOrganizer]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Test', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Test.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Test_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Test_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [DbOrganizer] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DbOrganizer].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DbOrganizer] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DbOrganizer] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DbOrganizer] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DbOrganizer] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DbOrganizer] SET ARITHABORT OFF 
GO

ALTER DATABASE [DbOrganizer] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DbOrganizer] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DbOrganizer] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DbOrganizer] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DbOrganizer] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DbOrganizer] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DbOrganizer] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DbOrganizer] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DbOrganizer] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DbOrganizer] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DbOrganizer] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DbOrganizer] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DbOrganizer] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DbOrganizer] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DbOrganizer] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DbOrganizer] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DbOrganizer] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DbOrganizer] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DbOrganizer] SET  MULTI_USER 
GO

ALTER DATABASE [DbOrganizer] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DbOrganizer] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DbOrganizer] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DbOrganizer] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DbOrganizer] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DbOrganizer] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DbOrganizer] SET  READ_WRITE 
GO

