//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientTaskOrganizer.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Task", Namespace="http://schemas.datacontract.org/2004/07/WCF_TaskOrganizer")]
    [System.SerializableAttribute()]
    public partial class Task : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Day {
            get {
                return this.DayField;
            }
            set {
                if ((this.DayField.Equals(value) != true)) {
                    this.DayField = value;
                    this.RaisePropertyChanged("Day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Month {
            get {
                return this.MonthField;
            }
            set {
                if ((this.MonthField.Equals(value) != true)) {
                    this.MonthField = value;
                    this.RaisePropertyChanged("Month");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((object.ReferenceEquals(this.PriorityField, value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/TaskOrganizer")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserLogin {
            get {
                return this.UserLoginField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLoginField, value) != true)) {
                    this.UserLoginField = value;
                    this.RaisePropertyChanged("UserLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPassword {
            get {
                return this.UserPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPasswordField, value) != true)) {
                    this.UserPasswordField = value;
                    this.RaisePropertyChanged("UserPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITaskOrganizer")]
    public interface ITaskOrganizer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskOrganizer/SelectAllFromDb", ReplyAction="http://tempuri.org/ITaskOrganizer/SelectAllFromDbResponse")]
        ClientTaskOrganizer.ServiceReference1.Task[] SelectAllFromDb(string userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskOrganizer/SelectAllFromDb", ReplyAction="http://tempuri.org/ITaskOrganizer/SelectAllFromDbResponse")]
        System.Threading.Tasks.Task<ClientTaskOrganizer.ServiceReference1.Task[]> SelectAllFromDbAsync(string userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskOrganizer/ConnectToDb", ReplyAction="http://tempuri.org/ITaskOrganizer/ConnectToDbResponse")]
        bool ConnectToDb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskOrganizer/ConnectToDb", ReplyAction="http://tempuri.org/ITaskOrganizer/ConnectToDbResponse")]
        System.Threading.Tasks.Task<bool> ConnectToDbAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskOrganizer/DisconnectFromDb", ReplyAction="http://tempuri.org/ITaskOrganizer/DisconnectFromDbResponse")]
        void DisconnectFromDb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskOrganizer/DisconnectFromDb", ReplyAction="http://tempuri.org/ITaskOrganizer/DisconnectFromDbResponse")]
        System.Threading.Tasks.Task DisconnectFromDbAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskOrganizer/DeleteRowInDb", ReplyAction="http://tempuri.org/ITaskOrganizer/DeleteRowInDbResponse")]
        void DeleteRowInDb(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskOrganizer/DeleteRowInDb", ReplyAction="http://tempuri.org/ITaskOrganizer/DeleteRowInDbResponse")]
        System.Threading.Tasks.Task DeleteRowInDbAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskOrganizer/AddRowsToDb", ReplyAction="http://tempuri.org/ITaskOrganizer/AddRowsToDbResponse")]
        void AddRowsToDb(ClientTaskOrganizer.ServiceReference1.Task task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskOrganizer/AddRowsToDb", ReplyAction="http://tempuri.org/ITaskOrganizer/AddRowsToDbResponse")]
        System.Threading.Tasks.Task AddRowsToDbAsync(ClientTaskOrganizer.ServiceReference1.Task task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskOrganizer/SaveChangesToDb", ReplyAction="http://tempuri.org/ITaskOrganizer/SaveChangesToDbResponse")]
        void SaveChangesToDb(ClientTaskOrganizer.ServiceReference1.Task[] task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskOrganizer/SaveChangesToDb", ReplyAction="http://tempuri.org/ITaskOrganizer/SaveChangesToDbResponse")]
        System.Threading.Tasks.Task SaveChangesToDbAsync(ClientTaskOrganizer.ServiceReference1.Task[] task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskOrganizer/ConfirmUser", ReplyAction="http://tempuri.org/ITaskOrganizer/ConfirmUserResponse")]
        bool ConfirmUser(ClientTaskOrganizer.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskOrganizer/ConfirmUser", ReplyAction="http://tempuri.org/ITaskOrganizer/ConfirmUserResponse")]
        System.Threading.Tasks.Task<bool> ConfirmUserAsync(ClientTaskOrganizer.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskOrganizer/AddUser", ReplyAction="http://tempuri.org/ITaskOrganizer/AddUserResponse")]
        bool AddUser(ClientTaskOrganizer.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskOrganizer/AddUser", ReplyAction="http://tempuri.org/ITaskOrganizer/AddUserResponse")]
        System.Threading.Tasks.Task<bool> AddUserAsync(ClientTaskOrganizer.ServiceReference1.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaskOrganizerChannel : ClientTaskOrganizer.ServiceReference1.ITaskOrganizer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaskOrganizerClient : System.ServiceModel.ClientBase<ClientTaskOrganizer.ServiceReference1.ITaskOrganizer>, ClientTaskOrganizer.ServiceReference1.ITaskOrganizer {
        
        public TaskOrganizerClient() {
        }
        
        public TaskOrganizerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaskOrganizerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskOrganizerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskOrganizerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientTaskOrganizer.ServiceReference1.Task[] SelectAllFromDb(string userLogin) {
            return base.Channel.SelectAllFromDb(userLogin);
        }
        
        public System.Threading.Tasks.Task<ClientTaskOrganizer.ServiceReference1.Task[]> SelectAllFromDbAsync(string userLogin) {
            return base.Channel.SelectAllFromDbAsync(userLogin);
        }
        
        public bool ConnectToDb() {
            return base.Channel.ConnectToDb();
        }
        
        public System.Threading.Tasks.Task<bool> ConnectToDbAsync() {
            return base.Channel.ConnectToDbAsync();
        }
        
        public void DisconnectFromDb() {
            base.Channel.DisconnectFromDb();
        }
        
        public System.Threading.Tasks.Task DisconnectFromDbAsync() {
            return base.Channel.DisconnectFromDbAsync();
        }
        
        public void DeleteRowInDb(int Id) {
            base.Channel.DeleteRowInDb(Id);
        }
        
        public System.Threading.Tasks.Task DeleteRowInDbAsync(int Id) {
            return base.Channel.DeleteRowInDbAsync(Id);
        }
        
        public void AddRowsToDb(ClientTaskOrganizer.ServiceReference1.Task task) {
            base.Channel.AddRowsToDb(task);
        }
        
        public System.Threading.Tasks.Task AddRowsToDbAsync(ClientTaskOrganizer.ServiceReference1.Task task) {
            return base.Channel.AddRowsToDbAsync(task);
        }
        
        public void SaveChangesToDb(ClientTaskOrganizer.ServiceReference1.Task[] task) {
            base.Channel.SaveChangesToDb(task);
        }
        
        public System.Threading.Tasks.Task SaveChangesToDbAsync(ClientTaskOrganizer.ServiceReference1.Task[] task) {
            return base.Channel.SaveChangesToDbAsync(task);
        }
        
        public bool ConfirmUser(ClientTaskOrganizer.ServiceReference1.User user) {
            return base.Channel.ConfirmUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> ConfirmUserAsync(ClientTaskOrganizer.ServiceReference1.User user) {
            return base.Channel.ConfirmUserAsync(user);
        }
        
        public bool AddUser(ClientTaskOrganizer.ServiceReference1.User user) {
            return base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> AddUserAsync(ClientTaskOrganizer.ServiceReference1.User user) {
            return base.Channel.AddUserAsync(user);
        }
    }
}
